Align with current practices

diff --git a/bin/git-pre-commit b/bin/git-pre-commit
--- a/bin/git-pre-commit
+++ b/bin/git-pre-commit
@@ -20,17 +20,16 @@
 #   > chmod u+x .git/hooks/pre-commit
 #
 
-has_error=0
+files="$(git diff-index --cached --name-only HEAD | grep -E '^.*\.(cpp|h|cs|uplugin|uproject)$')"
 
-for file in $(git diff-index --cached --name-only HEAD | grep -E '^(Plugins\/RuleRanger\/Source|Source)/.*\.(cpp|h|cs|uplugin)|*\.uproject$'); do
-    if [ -f $file ]; then
-        clang-format --dry-run --Werror -i "${file}" 2>/dev/null >/dev/null
-        if [ $? -ne 0 ]; then
-            clang-format -i "${file}"
-            echo "Commit aborted due to code format inconsistencies. '${file}' re-formatted, please review and update commit as required."
-            has_error=1
-        fi
-    fi
-done
+# shellcheck disable=SC2086
+python ./bin/format.py --dry-run $files
+echo python ./bin/format.py --dry-run $files
+if [ $? -ne 0 ]; then
+  # shellcheck disable=SC2086
+  python ./bin/format.py --verbose $files
+  echo "Commit aborted due to code format inconsistencies. Files re-formatted, please review and update commit as required."
+  exit 1
+fi
 
-exit ${has_error}
+exit 0
